services:
  - type: web
    name: codesense
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app/ui.py --server.port $PORT --server.enableCORS false
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
